name: re·app·ly
description: notes · thoughts · experiments · quirks · gimmicks
meta_description: "notes · thoughts · experiments · quirks · gimmicks"

aboutPage: true

# markdown: kramdown
# kramdown:
#   input: GFM
#   auto_ids: true
#   syntax_highlighting: rouge
markdown: kramdown
highlighter: rouge

gems: [jekyll-paginate]
paginate: 20
gems: [jekyll-paginate]
baseurl: /
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://your-blog-url.example.com'
author:         'Paul van Klaveren'
authorTwitter:  'apulmoes'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
